In [3]:
import numpy as np
print("NUMPY VERSION")
print(np.__version__)
print()
print("NUMPY CONFIGURATION")
print()
print(np.show_config())

NUMPY VERSION
1.23.4

NUMPY CONFIGURATION

openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros =

In [4]:
import numpy as np
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [6]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [7]:
l=[1,2,3,4,5]
a=np.array(l)
print(l)
print("REVERSE ARRAY")
print(l[::-1])

[1, 2, 3, 4, 5]
REVERSE ARRAY
[5, 4, 3, 2, 1]


In [8]:
from random import random
a=np.random.randn(3,3)
print(a)
print("Maximum value from array : ",a.max())
print("Minimum value from array : ",a.min())

[[-0.64995601 -1.69094169 -1.23775695]
 [-0.11804597  0.56766001 -0.75308116]
 [-0.15243068 -0.02007894 -1.87518387]]
Maximum value from array :  0.5676600146954315
Minimum value from array :  -1.8751838714290068


In [9]:
print("What is the result of the following expression?")
print("The answer is False.")


What is the result of the following expression?
The answer is False.


In [10]:
f=0
a=np.ones((5,5,8))
for i in range(5):
    for j in range(5):
        for k in range(8):
            if f==100:
                break
            f+=1
print("Index of 100th element: ","(",i,j,k,")")

Index of 100th element:  ( 4 4 0 )


In [11]:
ar1 = np.array([12, 14, 15, 16, 17])
ar2 = [12,19,21,17]

# Common values between two arrays
print(np.intersect1d(ar1, ar2))


[12 17]


In [12]:
k= np.random.random((10,2))
x,y = k[:,0], k[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.47346607 0.45127438 1.03257571 0.60471547 0.38089485 1.36052885
 0.90440573 0.7035799  0.26839939 0.7101975 ]
[1.28008301e+00 1.50889492e+00 4.46009951e-01 5.76680081e-01
 5.17919207e-02 7.77525856e-01 8.51256590e-02 1.37828167e+00
 1.39047202e-03 6.50835975e-01]


In [13]:
array = np.arange(100)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [14]:
t=np.arange(100,dtype='float32')
print(t)
t=t.astype('int32')
print(t)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
arr1=np.random.randn(1,3)
arr2=np.random.randn(3,1)
print(arr1)
print(arr2)
print(arr1+arr2)